import * as fs from 'fs';
import * as path from 'path';
import { runCoverage } from '../lib/coverage';
import { updateRun } from '../lib/supabase';
import type { Run, Gap } from '../lib/types';

/**
 * Phase 4 — Write approved tests to disk and re-run coverage.
 *
 * ⚠️  LOCKED: This phase MUST NOT run until the user has confirmed that the
 * Phase 3 human-approval gate is working correctly (both chat and dashboard
 * channels). The orchestrator entry point enforces this gate via the
 * `phase3Confirmed` parameter.
 *
 * For each approved/edited gap:
 *   - Derives the test file path from the source file (appending .test.ts)
 *   - Appends the draft_test code to that file (creates it if needed)
 *
 * After all writes:
 *   - Re-runs Vitest coverage in repoPath
 *   - Persists final_coverage to Supabase
 *   - Returns the new coverage %
 */
export async function runWritePhase(
  run: Run,
  approvedGaps: Gap[],
  repoPath: string
): Promise<number> {
  const writeable = approvedGaps.filter(
    (g) =>
      (g.approval_status === 'approved' || g.approval_status === 'edited') &&
      g.draft_test
  );

  if (writeable.length === 0) {
    console.log('[Phase 4] No approved tests to write.');
    const pct = await runCoverage(repoPath);
    await updateRun(run.id, {
      final_coverage: pct,
      completed_at: new Date().toISOString(),
    });
    return pct;
  }

  console.log(`[Phase 4] Writing ${writeable.length} approved test(s) to disk …`);

  for (const gap of writeable) {
    const absSourceFile = path.resolve(repoPath, gap.file);
    // Derive test file path: src/payments/charge.ts → src/payments/charge.test.ts
    const testFilePath = absSourceFile.replace(/\.(tsx?|jsx?)$/, '.test.$1');

    const header = `\n// ─── Auto-generated by Parallel Test-Gap Hunter ─────────────\n// Gap: ${gap.target} | Risk: ${gap.risk_score}\n// Rationale: ${gap.draft_rationale}\n\n`;
    const content = header + (gap.draft_test ?? '');

    if (fs.existsSync(testFilePath)) {
      fs.appendFileSync(testFilePath, content, 'utf-8');
      console.log(`[Phase 4]   Appended to ${path.relative(repoPath, testFilePath)}`);
    } else {
      fs.mkdirSync(path.dirname(testFilePath), { recursive: true });
      fs.writeFileSync(testFilePath, content, 'utf-8');
      console.log(`[Phase 4]   Created ${path.relative(repoPath, testFilePath)}`);
    }
  }

  console.log('[Phase 4] Re-running coverage …');
  const finalPct = runCoverage(repoPath);

  await updateRun(run.id, {
    final_coverage: finalPct,
    completed_at: new Date().toISOString(),
  });

  console.log(`[Phase 4] Final coverage: ${finalPct.toFixed(1)}%`);
  return finalPct;
}
